repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: books-ui
    labels:
      app: books-ui
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    values:
      - values.yaml
      - image:
          tag: "{{ .StateValues.image.tag }}"
      - ingress:
          hostname: "{{ .StateValues.ingress.hostname }}"
      - extraConfigMapEnvVars:
          LINK_TO_BOOKS_SERVICE: "{{ .StateValues.extraConfigMapEnvVars.LINK_TO_BOOKS_SERVICE }}"
          API_ROOT: "{{ .StateValues.extraConfigMapEnvVars.API_ROOT }}"
          API_ROOT_AUTH: "{{ .StateValues.extraConfigMapEnvVars.API_ROOT_AUTH }}"
          VITE_BASE_URL: "{{ .StateValues.extraConfigMapEnvVars.VITE_BASE_URL }}"