repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: books-ui
    labels:
      app: books-ui
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    values:
      - values.yaml
      - image:
          tag: "{{ .StateValues.image.tag }}"
      - ingress:
          hostname: "{{ .StateValues.ingress.hostname }}"
          annotations:
            # configuration-snippet is used to redirect from /b to /books saving query args
            nginx.ingress.kubernetes.io/configuration-snippet: "{{ .StateValues.redirectAnnotation }}"
          extraPaths:
            # additional path needed to set up redirect
            - path: "{{ .StateValues.ingress.extraPaths.path }}"
              pathType: ImplementationSpecific
              backend:
                service:
                  name: books-ui-nginx
                  port:
                    name: http
      - extraConfigMapEnvVars:
          API_ROOT_URL: "{{ .StateValues.extraConfigMapEnvVars.API_ROOT_URL }}"
          AUTH_API_ROOT_URL: "{{ .StateValues.extraConfigMapEnvVars.AUTH_API_ROOT_URL }}"